config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :auctions do
    resources :bids, only: [:new, :create, :index]
    patch 'close', to: 'auctions#close'
    collection do
      get :active
      get :off
    end
  end
  resources :bids, only: [:show, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auction.rb
class Auction < ApplicationRecord
  belongs_to :user
  has_many :bids, dependent: :destroy
  validates :initial_price, :item, :description, presence: true
  has_one_attached :photo
end

app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :user
  belongs_to :auction
end

app/models/user.rb
class User < ApplicationRecord
  has_many :auctions, dependent: :destroy
  has_many :bids, dependent: :destroy
  validates :email, :password, :first_name, :last_name, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo])
  end
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index]

  def index
    @auctions = Auction.all
    if params[:query]
      @auctions = Auction.joins(:user).where("
      auctions.item @@ :query OR
      users.first_name @@ :query OR
      users.last_name @@ :query
      ", query: params[:query])
    end
  end

  def show
    @auction = Auction.find(params[:id])
    @bid = @auction.bids.last
  end

  def new
    @auction = Auction.new
  end

  def create
    @auction = Auction.new(auctions_params)
    @auction.user = current_user

    if @auction.save
      redirect_to auction_path(@auction)
    else
      render :new
    end
  end

  def edit
    @auction = Auction.find(params[:id])
  end

  def update
    @auction = Auction.find(params[:id])
    if @auction.update(auctions_params)
      redirect_to auction_path(@auction), notice: 'auction updated successfully'
    else
      render :edit
    end
  end

  def destroy
    @auction = Auction.find(params[:id])
    @auction.destroy
    redirect_to auctions_path
  end

  def close
    @auction = Auction.find(params[:auction_id])
    @auction.update!(status: false)
    redirect_to auction_path(@auction)
  end

  def active
    @auctions = Auction.where(status: true)
  end

  def off
    @auctions = Auction.where(status: false)
  end

  private

  def auctions_params
    params.require(:auction).permit(:item, :description, :initial_price, :photo)
  end
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  def index
    @bids = Bid.all
  end

  def new
    @bid = Bid.new
  end

  def create
    @auction = Auction.find(params[:auction_id])

    if @auction.status
      price = @auction.bids.empty? ? @auction.initial_price : @auction.bids.last.price + rand(11..83)
      @bid = Bid.new(
        auction: @auction,
        user: current_user,
        price: price
      )
      if @bid.save
        redirect_to @auction, notice: 'bid was successfully created.'
      else
        render :new
      end
    else
      redirect_to @auction, alert: 'Auction already closed!'
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @auctions = Auction.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @auctions = Auction.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/auctions/active.html.erb
<div class="container justify-content space-between">
  <% if @auctions.present? %>
  <h1 class="title">Active Auctions</h1>

    <div class="row justify-content-between mx-auto">
        <% @auctions.each do |auction|%>
          <div class="card-category mx-1 my-2">
          <% if auction.photo.attached? %>
            <%= cl_image_tag auction.photo.key, class: 'card-product-img', height: 300, width: 350, crop: :fill %>
          <% else %>
            <%= image_tag("noimage.jpg", class: 'card-product-img', height: 300, width: 350, crop: :fill) %>
          <% end %>
            <div class="card-info">
              <p>Seller:  <%= auction.user.first_name.capitalize %></p>
              <p>Initial Price: <%= auction.initial_price %> US$</p>
              <p>Item Name: <%= auction.item %></p>
            <%= link_to "View Details", auction_path(auction), class: "btn" %>
            </div>
          </div>
        <% end %>
      </div>
  <% else %>
    <h1 class="title">Not Active Auctions</h1>
  <%end %>
</div>

app/views/auctions/edit.html.erb
<h1 class='container text-center'>Edit Your Auction</h1>

<div class='container text-center'>
  <%= simple_form_for(@auction) do |f| %>
    <%= f.input :item, label: 'Item Name' %>
    <%= f.input :description, label: 'Description' %>
    <%= f.input :initial_price, label: 'Initial Price' %>
    <%= f.input :photo, as: :file %>
    <%= f.submit %>
  <% end %>
</div>

app/views/auctions/index.html.erb
<%# <form novalidate="novalidate" class="simple_form search" action="/" accept-charset="UTF-8" method="get"><input name="utf8" type="hidden" value="&#x2713;" />
  <div class="search-form-control form-group">
    <input class="form-control string required" type="text" name="params[:query]" id="search_query" />
    <button name="button" type="submit" class="btn btn-primary">
      <i class="fas fa-search"></i> Search
    </button>
  </div>
</form> %>
<div class="container justify-content space-between">
  <h1 class='title'>All Auctions</h1>
  <%= form_tag auctions_path, method: :get do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Find a Auction"%>
    <%= submit_tag "Search", class: "btn-Search" %>
  <% end %>

  <div>
    <div class="row justify-content-between mx-auto">
      <% @auctions.each do |auction|%>
        <div class="card-category mx-1 my-2 ">
          <% if auction.photo.attached? %>
            <%= cl_image_tag auction.photo.key, class: 'card-product-img', height: 300, width: 350, crop: :fill %>
          <% else %>
            <%= image_tag("noimage.jpg", class: 'card-product-img', height: 300, width: 350, crop: :fill) %>
          <% end %>
          <div class="card-info">
              <p>Seller:  <%= auction.user.first_name.capitalize %></p>
              <p>Initial Price: <%= auction.initial_price %> US$</p>
              <p>Item Name: <%= auction.item %></p>
              <%= link_to "View Details", auction_path(auction), class: "btn px-5" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="text-center">
    <%= link_to "Create a Auctions", new_auction_path, class: "btn px-5" %>
  </div>
</div>

app/views/auctions/new.html.erb
<h1 class='container text-center'>Create your Auction</h1>

<div class='container text-center' id='formcolor'>
  <%= simple_form_for @auction do |f| %>
    <%= f.input :item, label: 'Nome do item' %>
    <%= f.input :description, label: 'Description' %>
    <%= f.input :initial_price, label: 'Initial Price' %>
    <%= f.input :photo, as: :file %>
    <%= f.submit class: "btn btn-primary btn-lg" %>
  <% end %>
</div>

app/views/auctions/off.html.erb
<div class="container justify-content space-between">
  <% if @auctions.present? %>
  <h1 class="title">Off Auctions</h1>

    <div class="row justify-content-between mx-auto">
        <% @auctions.each do |auction|%>
          <div class="card-category mx-1 my-2">
          <% if auction.photo.attached? %>
            <%= cl_image_tag auction.photo.key, class: 'card-product-img', height: 300, width: 350, crop: :fill %>
          <% else %>
            <%= image_tag("noimage.jpg", class: 'card-product-img', height: 300, width: 350, crop: :fill) %>
          <% end %>
            <div class="card-info">
              <p>Seller:  <%= auction.user.first_name.capitalize %></p>
              <p>Initial Price: <%= auction.initial_price %> US$</p>
              <p>Item Name: <%= auction.item %></p>
            <%= link_to "View Details", auction_path(auction), class: "btn" %>
            </div>
          </div>
        <% end %>
      </div>
  <% else %>
    <h1 class="title">Not Closed Auctions</h1>
  <%end %>
  <%= link_to "Go to All Auctions", auctions_path, class: "btn" %>
</div>

app/views/auctions/show.html.erb
<h1 class="title">Details</h1>

<div class="container">
  <div class="card-product row">

    <% if @auction.photo.attached? %>
      <%= cl_image_tag @auction.photo.key, class: "card-product-img col-3" %>
    <%else %>
      <%= image_tag("noimage.jpg")%>
    <% end %>
  <div class="card-product-infos col-4">


    <% if @auction.user.photo.attached? %>
      <%= cl_image_tag @auction.user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
    <%else %>
      <%= image_tag "noimage.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
    <% end %>

    <h2>Auctioneer: <%= @auction.user.first_name.capitalize %></h2>
    <p>Item: <%= @auction.item %> </p>
    <p>Description: <%= @auction.description %> </p>
    <p>Initial Price: <%= @auction.initial_price %>,00 US$</p>
  </div>
  <div class="col-4 justify-content-center">

    <h3><% if @bid.present? %>
          Current Bid: <strong><%= @bid.price  %>,00 US$</strong>
          <% if @auction.bids[-2].present? %>
          <br>
            Previous Bid:<%=@auction.bids[-2].user.first_name %>
            <%=@auction.bids[-2].price %>,00 US$
          <% end %>
        <%else%>
          NO BIDS YET! Min bid <%= @auction.initial_price %> !
        <% end %>

        <% if @auction.status %>
          <p> Auction OPEN! </p>
          <%= link_to "Bid", auction_bids_path(@auction), method: :post, class: "btn" if @auction.user != current_user %>
        <% else %>
          <p>Auction CLOSED!</p>
          <%# <%=@bid.present? ? "Winner: #{@bid.user.first_name}" : "Not Winner....."%>
          <% if @bid.present? %>
            <%="Winner: #{@bid.user.first_name}" %>
            <% if @bid.user.photo.attached? %>
              <%= cl_image_tag @bid.user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <%else %>
              <%= image_tag "noimage.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false%>
            <% end %>
          <% else %>
            "Not Winner.....
          <% end %>

        <% end %>
      </h3>
    </div>
  </div>

  <%= link_to "View Auctions", auctions_path, class: "btn" %>

  <% if @auction.user == current_user %>
    <%= link_to "Close auction", auction_close_path(@auction), method: :patch, class: "btn" %>
    <%= link_to "Edit Auctions", edit_auction_path(@auction), class: "btn" %>
    <%= link_to "Delete", auction_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn" %>
  <% end %>

</div>

app/views/bids/new.html.erb
<div class="container">
  <h1>Entre com o seu lance</h1>

    <div class='container text-center'>
      <%= simple_form_for @bid do |f| %>
        <%= f.input :price, label: 'valor' %>
        <%= f.submit class: "btn btn-primary btn-lg" %>
      <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlackMarket</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body class="pb-5 mb-3">
    <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>

  <div class="footer fixed-bottom">
    <div class="footer-links">
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
    </div>
      <div class="footer-copyright">
        TAT Incorporated
      </div>
  </div>
</html>

app/views/pages/home.html.erb
<div id="foto" class="pr-5">
  <div class="home-btn">
    <div><h1 id="colorhome"></h1></div>
  </div>
    <br><%= link_to "View Auctions", auctions_path, class: "btn" %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div>
    <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMnSIA4pzhFkxKlheo07m52uA65Drlfp5nrQ&usqp=CAU" %>
    <strong>Black Market batch#690</strong>
    <% end %>
  </div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>

        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "All Auctions", auctions_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Active Auctions", active_auctions_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Off Auctions", off_auctions_path, class: "nav-link" %>
        </li>

        <li class="nav-item dropdown">
        <% if current_user.photo.attached? %>
          <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <%else %>
          <%= image_tag "noimage.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "New Auction", new_auction_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>